packages:
  - 'packages/*'
  - 'examples/*'

# Optional: Catalog for shared dependency versions
catalog:
  typescript: ^5.3.2
  vite: ^5.0.2
  '@types/node': ^20.10.0
  vitest: ^1.0.0
  eslint: ^8.54.0
  prettier: ^3.1.0